const keys = {
  en: [
    {
      key: '`',
      keyCaps: '`',
      keyShift: '~',
      keyCode: 192,
    },
    {
      key: '1',
      keyCaps: '1',
      keyShift: '!',
      keyCode: 49,
    },
    {
      key: '2',
      keyCaps: '2',
      keyShift: '@',
      keyCode: 50,
    },
    {
      key: '3',
      keyCaps: '3',
      keyShift: '#',
      keyCode: 51,
    },
    {
      key: '4',
      keyCaps: '4',
      keyShift: '$',
      keyCode: 52,
    },
    {
      key: '5',
      keyCaps: '5',
      keyShift: '%',
      keyCode: 53,
    },
    {
      key: '6',
      keyCaps: '6',
      keyShift: '^',
      keyCode: 54,
    },
    {
      key: '7',
      keyCaps: '7',
      keyShift: '*',
      keyCode: 55,
    },
    {
      key: '8',
      keyCaps: '8',
      keyShift: '*',
      keyCode: 56,
    },
    {
      key: '9',
      keyCaps: '9',
      keyShift: '(',
      keyCode: 57,
    },
    {
      key: '0',
      keyCaps: '0',
      keyShift: ')',
      keyCode: 48,
    },
    {
      key: '-',
      keyCaps: '-',
      keyShift: '_',
      keyCode: 189,
    },
    {
      key: '=',
      keyCaps: '=',
      keyShift: '+',
      keyCode: 187,
    },
    {
      key: 'Backspace',
      keyCaps: 'Backspace',
      keyShift: 'Backspace',
      keyCode: 8,
    },
    {
      key: 'Tab',
      keyCaps: 'Tab',
      keyShift: 'Tab',
      keyCode: 9,
    },
    {
      key: 'q',
      keyCaps: 'Q',
      keyShift: 'Q',
      keyCode: 81,
    },
    {
      key: 'w',
      keyCaps: 'W',
      keyShift: 'W',
      keyCode: 87,
    },
    {
      key: 'e',
      keyCaps: 'E',
      keyShift: 'E',
      keyCode: 69,
    },
    {
      key: 'r',
      keyCaps: 'R',
      keyShift: 'R',
      keyCode: 82,
    },
    {
      key: 't',
      keyCaps: 'T',
      keyShift: 'T',
      keyCode: 84,
    },
    {
      key: 'y',
      keyCaps: 'Y',
      keyShift: 'Y',
      keyCode: 89,
    },
    {
      key: 'u',
      keyCaps: 'U',
      keyShift: 'U',
      keyCode: 85,
    },
    {
      key: 'i',
      keyCaps: 'I',
      keyShift: 'I',
      keyCode: 73,
    },
    {
      key: 'o',
      keyCaps: 'O',
      keyShift: 'O',
      keyCode: 79,
    },
    {
      key: 'p',
      keyCaps: 'P',
      keyShift: 'P',
      keyCode: 80,
    },
    {
      key: '[',
      keyCaps: '[',
      keyShift: '{',
      keyCode: 219,
    },
    {
      key: ']',
      keyCaps: ']',
      keyShift: '}',
      keyCode: 221,
    },
    {
      key: 'Enter',
      keyCaps: 'Enter',
      keyShift: 'Enter',
      keyCode: 13,
    },
    {
      key: 'CapsLock',
      keyCaps: 'CapsLock',
      keyShift: 'CapsLock',
      keyCode: 20,
    },
    {
      key: 'a',
      keyCaps: 'A',
      keyShift: 'A',
      keyCode: 65,
    },
    {
      key: 's',
      keyCaps: 'S',
      keyShift: 'S',
      keyCode: 83,
    },
    {
      key: 'd',
      keyCaps: 'D',
      keyShift: 'D',
      keyCode: 68,
    },
    {
      key: 'f',
      keyCaps: 'F',
      keyShift: 'F',
      keyCode: 70,
    },
    {
      key: 'g',
      keyCaps: 'G',
      keyShift: 'G',
      keyCode: 71,
    },
    {
      key: 'h',
      keyCaps: 'H',
      keyShift: 'H',
      keyCode: 72,
    },
    {
      key: 'j',
      keyCaps: 'J',
      keyShift: 'J',
      keyCode: 74,
    },
    {
      key: 'k',
      keyCaps: 'K',
      keyShift: 'K',
      keyCode: 75,
    },
    {
      key: 'l',
      keyCaps: 'L',
      keyShift: 'L',
      keyCode: 76,
    },
    {
      key: ';',
      keyCaps: ';',
      keyShift: ':',
      keyCode: 186,
    },
    {
      key: "'",
      keyCaps: "'",
      keyShift: '"',
      keyCode: 222,
    },
    {
      key: 'Up',
      keyCaps: 'Up',
      keyShift: 'Up',
      keyCode: 38,
    },
    {
      key: '\\',
      keyCaps: '\\',
      keyShift: '|',
      keyCode: 220,
    },
    {
      key: 'Shift',
      keyCaps: 'Shift',
      keyShift: 'Shift',
      keyCode: 16,
    },
    {
      key: 'z',
      keyCaps: 'Z',
      keyShift: 'Z',
      keyCode: 90,
    },
    {
      key: 'x',
      keyCaps: 'X',
      keyShift: 'X',
      keyCode: 88,
    },
    {
      key: 'c',
      keyCaps: 'C',
      keyShift: 'C',
      keyCode: 67,
    },
    {
      key: 'v',
      keyCaps: 'V',
      keyShift: 'V',
      keyCode: 86,
    },
    {
      key: 'b',
      keyCaps: 'B',
      keyShift: 'B',
      keyCode: 66,
    },
    {
      key: 'n',
      keyCaps: 'N',
      keyShift: 'N',
      keyCode: 78,
    },
    {
      key: 'm',
      keyCaps: 'M',
      keyShift: 'M',
      keyCode: 77,
    },
    {
      key: ',',
      keyCaps: ',',
      keyShift: '<',
      keyCode: 188,
    },
    {
      key: '.',
      keyCaps: '.',
      keyShift: '>',
      keyCode: 190,
    },
    {
      key: '/',
      keyCaps: '/',
      keyShift: '?',
      keyCode: 191,
    },
    {
      key: 'Left',
      keyCaps: 'Left',
      keyShift: 'Left',
      keyCode: 37,
    },
    {
      key: 'Down',
      keyCaps: 'Down',
      keyShift: 'Down',
      keyCode: 40,
    },
    {
      key: 'Right',
      keyCaps: 'Right',
      keyShift: 'Right',
      keyCode: 39,
    },
    {
      key: 'Ctrl',
      keyCaps: 'Ctrl',
      keyShift: 'Ctrl',
      keyCode: 17,
    },
    {
      key: 'Alt',
      keyCaps: 'Alt',
      keyShift: 'Alt',
      keyCode: 18,
    },
    {
      key: ' ',
      keyCaps: ' ',
      keyShift: ' ',
      keyCode: 32,
    },
    {
      key: 'Win',
      keyCaps: 'Win',
      keyShift: 'Win',
      keyCode: 91,
    },
  ],
  ru: [
    {
      key: 'ё',
      keyCaps: 'Ё',
      keyShift: 'Ё',
      keyCode: 192,
    },
    {
      key: '1',
      keyCaps: '1',
      keyShift: '!',
      keyCode: 49,
    },
    {
      key: '2',
      keyCaps: '2',
      keyShift: '"',
      keyCode: 50,
    },
    {
      key: '3',
      keyCaps: '3',
      keyShift: '№',
      keyCode: 51,
    },
    {
      key: '4',
      keyCaps: '4',
      keyShift: ';',
      keyCode: 52,
    },
    {
      key: '5',
      keyCaps: '5',
      keyShift: '%',
      keyCode: 53,
    },
    {
      key: '6',
      keyCaps: '6',
      keyShift: ':',
      keyCode: 54,
    },
    {
      key: '7',
      keyCaps: '7',
      keyShift: '?',
      keyCode: 55,
    },
    {
      key: '8',
      keyCaps: '8',
      keyShift: '*',
      keyCode: 56,
    },
    {
      key: '9',
      keyCaps: '9',
      keyShift: '(',
      keyCode: 57,
    },
    {
      key: '0',
      keyCaps: '0',
      keyShift: ')',
      keyCode: 48,
    },
    {
      key: '-',
      keyCaps: '-',
      keyShift: '_',
      keyCode: 189,
    },
    {
      key: '=',
      keyCaps: '=',
      keyShift: '+',
      keyCode: 187,
    },
    {
      key: 'Backspace',
      keyCaps: 'Backspace',
      keyShift: 'Backspace',
      keyCode: 8,
    },
    {
      key: 'Tab',
      keyCaps: 'Tab',
      keyShift: 'Tab',
      keyCode: 9,
    },
    {
      key: 'й',
      keyCaps: 'Й',
      keyShift: 'Й',
      keyCode: 81,
    },
    {
      key: 'ц',
      keyCaps: 'Ц',
      keyShift: 'Ц',
      keyCode: 87,
    },
    {
      key: 'у',
      keyCaps: 'У',
      keyShift: 'У',
      keyCode: 69,
    },
    {
      key: 'к',
      keyCaps: 'К',
      keyShift: 'К',
      keyCode: 82,
    },
    {
      key: 'е',
      keyCaps: 'Е',
      keyShift: 'Е',
      keyCode: 84,
    },
    {
      key: 'н',
      keyCaps: 'Н',
      keyShift: 'Н',
      keyCode: 89,
    },
    {
      key: 'г',
      keyCaps: 'Г',
      keyShift: 'Г',
      keyCode: 85,
    },
    {
      key: 'ш',
      keyCaps: 'Ш',
      keyShift: 'Ш',
      keyCode: 73,
    },
    {
      key: 'щ',
      keyCaps: 'Щ',
      keyShift: 'Щ',
      keyCode: 79,
    },
    {
      key: 'з',
      keyCaps: 'З',
      keyShift: 'З',
      keyCode: 80,
    },
    {
      key: 'х',
      keyCaps: 'Х',
      keyShift: 'Х',
      keyCode: 219,
    },
    {
      key: 'ъ',
      keyCaps: 'Ъ',
      keyShift: 'Ъ',
      keyCode: 221,
    },
    {
      key: 'Enter',
      keyCaps: 'Enter',
      keyShift: 'Enter',
      keyCode: 13,
    },
    {
      key: 'CapsLock',
      keyCaps: 'CapsLock',
      keyShift: 'CapsLock',
      keyCode: 20,
    },
    {
      key: 'ф',
      keyCaps: 'Ф',
      keyShift: 'Ф',
      keyCode: 65,
    },
    {
      key: 'ы',
      keyCaps: 'Ы',
      keyShift: 'Ы',
      keyCode: 83,
    },
    {
      key: 'в',
      keyCaps: 'В',
      keyShift: 'В',
      keyCode: 68,
    },
    {
      key: 'а',
      keyCaps: 'А',
      keyShift: 'А',
      keyCode: 70,
    },
    {
      key: 'п',
      keyCaps: 'П',
      keyShift: 'П',
      keyCode: 71,
    },
    {
      key: 'р',
      keyCaps: 'Р',
      keyShift: 'Р',
      keyCode: 72,
    },
    {
      key: 'о',
      keyCaps: 'О',
      keyShift: 'О',
      keyCode: 74,
    },
    {
      key: 'л',
      keyCaps: 'Л',
      keyShift: 'Л',
      keyCode: 75,
    },
    {
      key: 'д',
      keyCaps: 'Д',
      keyShift: 'Д',
      keyCode: 76,
    },
    {
      key: 'ж',
      keyCaps: 'Ж',
      keyShift: 'Ж',
      keyCode: 186,
    },
    {
      key: 'э',
      keyCaps: 'Э',
      keyShift: 'Э',
      keyCode: 222,
    },
    {
      key: 'Up',
      keyCaps: 'Up',
      keyShift: 'Up',
      keyCode: 38,
    },
    {
      key: '\\',
      keyCaps: '\\',
      keyShift: '/',
      keyCode: 220,
    },
    {
      key: 'Shift',
      keyCaps: 'Shift',
      keyShift: 'Shift',
      keyCode: 16,
    },
    {
      key: 'я',
      keyCaps: 'Я',
      keyShift: 'Я',
      keyCode: 90,
    },
    {
      key: 'ч',
      keyCaps: 'Ч',
      keyShift: 'Ч',
      keyCode: 88,
    },
    {
      key: 'с',
      keyCaps: 'С',
      keyShift: 'С',
      keyCode: 67,
    },
    {
      key: 'м',
      keyCaps: 'М',
      keyShift: 'М',
      keyCode: 86,
    },
    {
      key: 'и',
      keyCaps: 'И',
      keyShift: 'И',
      keyCode: 66,
    },
    {
      key: 'т',
      keyCaps: 'Т',
      keyShift: 'Т',
      keyCode: 78,
    },
    {
      key: 'ь',
      keyCaps: 'Ь',
      keyShift: 'Ь',
      keyCode: 77,
    },
    {
      key: 'б',
      keyCaps: 'Б',
      keyShift: 'Б',
      keyCode: 188,
    },
    {
      key: 'ю',
      keyCaps: 'Ю',
      keyShift: 'Ю',
      keyCode: 190,
    },
    {
      key: '.',
      keyCaps: '.',
      keyShift: ',',
      keyCode: 191,
    },
    {
      key: 'Left',
      keyCaps: 'Left',
      keyShift: 'Left',
      keyCode: 37,
    },
    {
      key: 'Down',
      keyCaps: 'Down',
      keyShift: 'Down',
      keyCode: 40,
    },
    {
      key: 'Right',
      keyCaps: 'Right',
      keyShift: 'Right',
      keyCode: 39,
    },
    {
      key: 'Ctrl',
      keyCaps: 'Ctrl',
      keyShift: 'Ctrl',
      keyCode: 17,
    },
    {
      key: 'Alt',
      keyCaps: 'Alt',
      keyShift: 'Alt',
      keyCode: 18,
    },
    {
      key: ' ',
      keyCaps: ' ',
      keyShift: ' ',
      keyCode: 32,
    },
    {
      key: 'Win',
      keyCaps: 'Win',
      keyShift: 'Win',
      keyCode: 91,
    },
  ],
};

export default keys;